#!/home/sasha/Documents/fontography/opentype-svg/venv/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'opentypesvg==1.1.1','console_scripts','addsvg'
__requires__ = 'opentypesvg==1.1.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('opentypesvg==1.1.1', 'console_scripts', 'addsvg')()
    )
